/*
 * This source file was generated by the Gradle 'init' task
 */
package javaproject;

import java.util.ArrayList;

public class App {

    String woodType;
    int woodDurability;
    
    public App(String type, int durability){
        woodType = type;
        woodDurability = durability;
    }

    public String getGreeting() {
        int testInt = 15;
        int testInt2 = 0;
        /**if (testInt > 15){
            testInt *= 4;
            return String.valueOf(testInt);
        }
        else if (testInt < 15) {
            testInt *= 3;
            return String.valueOf(testInt);
        }
        else {
            testInt *= 2;
            return String.valueOf(testInt);
        }**/

        /**switch (testInt) {
            case 15:
                System.out.println(testInt);
                break;
            case 12:
                System.out.println(testInt);
                break;
            case 13:
                System.out.println(testInt);
                break;
        }**/

        /**while (testInt2 < testInt) {
            System.out.println(testInt2);
            testInt2++;
        }**/

        //String [] rules = {"efgfd", "erweqwd", "efrerfweqw"};
        ArrayList <String> car = new ArrayList<String>();

        car.add("tires");
        car.add("windows");
        car.add("doors");
        car.add("tint");
        car.add("gears");
        car.set(1, "windshield");
        //car.remove("window");

        for (int i = 0; i < car.size(); i++) {
            System.out.println(car.get(i));
        }


        return "";
    }

    public static void main(String[] args) {
        //App wood1 = new App("timber", 120);
        //System.out.println(wood1.woodType);
        //System.out.println(new App("timber", 120).getGreeting());
        App2 myApp2 = new App2();
        System.out.println(myApp2.getCards());
    }
}
