/*
 * This source file was generated by the Gradle 'init' task
 */
package returnproject;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test void appHasAGreeting() {
        App classUnderTest = new App();
        assertTrue(classUnderTest.count() == 5);
    }
}
