/*
 * This source file was generated by the Gradle 'init' task
 */
package returnproject;

public class App {
    public static int count() {
        return 5;
    }

    public static void main(String[] args) {
        DummyJava testDJ = new DummyJava();
        testDJ.setFoodName("Fifal");
        System.out.println(testDJ.getName());
    }
}
