/*
 * This source file was generated by the Gradle 'init' task
 */
package returnproject;

public class App {
    public static int count() {
        return 5;
    }

    public static void main(String[] args) {
        System.out.println(new App().count());
    }
}
